#!/usr/bin/env sh
. "$(readlink -f $(dirname $(readlink -f $HOME/.xinitrc))/../)/test/lib"
run_test () {
  echo -n "$1: "
  export RUNNING_SHELL="$(basename "$(readlink -f "$(which "$1")")")"
  path_hasbin $1 && $1 $(dirname "$0")/test
  echo ""
}
run_test bash
run_test zsh
run_test dash
run_test sh
