#!/bin/sh
FILE=`readlink -f $0`
DIR=`dirname $FILE`

#UPDATE SUBMODULES IF THEY HAVEN'T BEEN
if [ "$1" != "1" ]; then
	git submodule foreach --recursive "${DIR}/base/update-git"
fi

#INSTALL CONFIGS
CONF="gvimrc vimrc bash_profile bashrc bash_logout zshrc zprofile"
for i in $CONF; do
	rm -f ~/.$i
	ln -sv ${DIR}/base/$i ~/.$i
done

#LINK PRELUDE
rm -f ~/.emacs
rm -rf ~/.emacs.d
ln -s ${DIR}/prelude ~/.emacs.d

#SETUP ZSH IF POSSIBLE
echo $SHELL | grep zsh >/dev/null 2>&1
if [ "$?" != "0" ]; then
	ZSH=`which zsh 2>/dev/null`
	if [ "$?" = "0" ]; then
		chsh $USER -s $ZSH
		if [ "$?" != "0" ]; then
			rm -fv ~/.bash_profile
			ln -sv ${DIR}/base/bash_profile_zsh ~/.bash_profile
		fi
	fi
fi

#SETUP SSH
if [[ ! -d ~/.ssh || ! -f ~/.ssh/id_rsa ]]; then
	echo "Creating SSH Keys"
	${DIR}/install-ssh-keys
fi
