#!/bin/bash
mkdir -p ~/.ssh
rm -f ~/.ssh/authorized_keys
if [ "$1" = "rsa" ]; then
	cat ssh/*_rsa >> ~/.ssh/authorized_keys
elif [ "$1" = "ecdsa" ]; then
	cat ssh/*_ecdsa >> ~/.ssh/authorized_keys
else
	echo "You must select either rsa or ecdsa"
fi
