#!/bin/bash
DIR="${HOME}/.ssh"
#DIR="."
stty -echo
read -p "Password: " pass
echo ""
read -p "Confirm: " pass2
echo ""
stty echo
if [ "$pass" != "$pass2" ]; then
	echo "Passwords do not match"
	exit 1
fi
if [ "$pass" = "" ]; then
	openssl genrsa -out ${DIR}/id_rsa 4096
else
	openssl genrsa -aes256 -passout "pass:${pass}" -out ${DIR}/id_rsa 4096
fi
chmod 0700 ${DIR}/id_rsa
if [ "$pass" = "" ]; then
	echo `ssh-keygen -yf ${DIR}/id_rsa` `hostname` > ${DIR}/id_rsa.pub
else
	echo `ssh-keygen -P $pass -yf ${DIR}/id_rsa` `hostname` > ${DIR}/id_rsa.pub
fi
if [ "$pass" = "" ]; then
	openssl ecparam -genkey -name secp521r1 -out ${DIR}/id_ecdsa
else
	openssl ecparam -genkey -name secp521r1 | openssl ec -aes256 -passout "pass:$pass" -out ${DIR}/id_ecdsa
fi
chmod 0700 ${DIR}/id_ecdsa
if [ "$pass" = "" ]; then
	echo `ssh-keygen -yf ${DIR}/id_ecdsa` `hostname` > ${DIR}/id_ecdsa.pub
else
	echo `ssh-keygen -P $pass -yf ${DIR}/id_ecdsa` `hostname` > ${DIR}/id_ecdsa.pub
fi
exit 0
