#!/usr/bin/env sh
git remote set-url origin https://github.com/wkennington/config
git remote set-url --push origin git@github.com:wkennington/config
$(dirname "$0")/bin/run config_latest
[ "$?" -le "1" ] || exit 1
$(dirname "$0")/bin/run config_install || exit 2
