#!/bin/sh
FILE=`readlink -f $0`
DIR=`dirname $FILE`

#UPDATE SUBMODULES IF THEY HAVEN'T BEEN
if [ "$1" != "1" ]; then
	"${DIR}/base/update-git2" 1
	exit 0
fi

#INSTALL CONFIGS
CONF="gvimrc vimrc bash_profile bashrc bash_logout zshrc zprofile zlogout"
for i in $CONF; do
	rm -f ~/.$i
	ln -s ${DIR}/base/$i ~/.$i
done

# USE EMACS
EMACS="$(which emacs 2>/dev/null | grep -v "not found")"
if [ "$EMACS" != "" ]; then
	rm -rf "${HOME}/.emacs.d"
	rm -f "${HOME}/.emacs"
	ln -s "${DIR}/base/emacs.d" "${HOME}/.emacs.d"
fi

#SETUP ZSH IF POSSIBLE
echo $SHELL | grep zsh >/dev/null 2>&1
if [ "$?" != "0" ]; then
	ZSH="$(which zsh 2>/dev/null | grep -v "not found")"
	if [ "$ZSH" != "" ]; then
		VER="$(${ZSH} --version | awk '{print $2}')"
		VER="$(printf "4.3.9\n%s" "$VER" | sort -bt. -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n | awk 'NR==1')"
		cat /etc/issue 2>/dev/null | grep "Arch Linux" >/dev/null 2>&1 || uname | grep "FreeBSD" >/dev/null
		if [ "$?" = "0" ]; then
			if [ "$VER" = "4.3.9" ]; then
				chsh -s "$ZSH" "$USER"
				if [ "$?" != "0" ]; then
					rm -fv ~/.bash_profile
					ln -s ${DIR}/base/bash_profile_zsh ~/.bash_profile
				fi
			fi
		fi
	fi
fi

# SETUP SSH
if [ ! -f ~/.ssh/id_rsa.pub ]; then
	echo "Creating SSH Keys"
	${DIR}/install-ssh-keys
fi
ssh-keygen -H >/dev/null 2>&1
rm -f ~/.ssh/known_hosts.old
rm -f ~/.ssh/config
ln -s "${DIR}/base/ssh_config" ~/.ssh/config
