#!/bin/sh
FILE=`readlink -f $0`
DIR=`dirname $FILE`/awesome
rm -rf ~/.{xinitrc,Xdefaults,gtkrc-2.0,config/{awesome,sakura,gtk-3.0,Terminal,wallpaper}}
install -dv ~/.config
#ln -sv $DIR/gtkrc-2.0 ~/.gtkrc-2.0
ln -s $DIR/xinitrc ~/.xinitrc
ln -s $DIR/awesome ~/.config/awesome
ln -s $DIR/Terminal ~/.config/Terminal
ln -s $DIR/wallpaper ~/.config/wallpaper
#ln -sv $DIR/sakura ~/.config/sakura
#ln -sv $DIR/gtk-3.0 ~/.config/gtk-3.0
#ln -sv $DIR/Xdefaults ~/.Xdefaults
