#!/bin/sh
DIR="$(dirname "$(readlink -f "$0")")"
cd $DIR
. ./integrity

# Required Programs
require_all

# Check for Valid Arguments
if [ "$#" -ne "1" ]; then
	echo "$0 message" >&2
	exit 1
fi

# Commit Current Changes
date -u +%s > .date
git add .date
git commit -m "$1"

# Sign and Commit Signature
hash_commit "HEAD" > .hash
rm -f .sig
gpg -bo .sig .hash
git add .hash .sig
git commit -m "Signing Commit"
git push origin master
