#!/bin/sh
DIR="$(dirname "$(readlink -f "$0")")"
cd $DIR
. ./integrity

# Required Programs
require_all

# Invalid Arguments?
if [ "$#" -gt "1" ]; then
fi
gpg --verify .sig .hash
echo "Invalid Directory Signature" >&2
exit 1
