#!/bin/sh
DIR="$(dirname "$(readlink -f "$0")")"
cd $DIR
. ./integrity

# Required Programs
require_all

# Get the latest Commits
gpg --verify .sig .hash
echo "Invalid Directory Signature" >&2
exit 1
