autocutsel -fork &
autocutsel -selection PRIMARY -fork &
while true;
do
	awsetbg -r git/projects/wallpaper
	sleep 5m
done &
#wicd-gtk &
#wuala &
pulseaudio --start
xscreensaver -no-splash &
./.xinitrc.local
exec ck-launch-session dbus-launch awesome
./.xinitrc.local.end
pulseaudio --kill &
