which autocutsel
if [ "$?" = "0" ]; then
	autocutsel -fork &
fi
if [[ -d ~/.config/wallpaper && "`ls ~/.config/wallpaper` | wc -l" > "1" ]]; then
	while true;
	do
		awsetbg -r ~/.config/wallpaper
		sleep 5m
	done &
fi
which pulseaudio >/dev/null 2>&1 && pulseaudio --start
which xscreensaver >/dev/null 2>&1 && xscreensaver -no-splash &
which VBoxClient-all >/dev/null 2>&1 && VBoxClient-all &
./.xinitrc.local
exec ck-launch-session dbus-launch $1
./.xinitrc.local.end
which pulseaudio >/dev/null 2>&1 && pulseaudio --kill &
