#!/usr/bin/env sh

# Exports extra params
agent_export () {
  export SSH_AUTH_SOCK
  export GPG_AGENT_INFO
  export GNOME_KEYRING_CONTROL
  export GNOME_KEYRING_PID
}

# Retrieve the agent environment
agent_file () {
  echo "$(dir_tmp)/agent-environment"
}

# Print cmd if agent exists
agent_cmd () {
  [ "$#" -lt "1" ] && return 1
  path_hasbin $1 && echo $@
}

# Determine which agent to use
agent_which () {
  [ "$(hostname -s )" = "fantom" ] && agent_cmd ssh-agent && return 0
  agent_cmd gnome-keyring-daemon -c pkcs11,secrets
  [ "$SSH_TTY" = "" ] && agent_cmd gpg-agent --daemon --enable-ssh-support && return 0
  agent_cmd ssh-agent && return 0
  echo "Failed to find an agent" >&2
  return 1
}

# Tests to see if the agent is already running
agent_running () {
  run_quiet ssh-add -L
  [ "$?" -ne "2" ]
}

# Import already running agent data
agent_env () {
  [ -f "$(agent_file)" ] && . "$(agent_file)"
  agent_export
  agent_running
}

# Spawn agent if it doesn't exist
agent_spawn () {
  echo "Spawning $@"
  (eval "$@") | grep -v echo > "$(agent_file)"
  agent_env
  ssh-add
}

# Automatically determines which agent to use and starts it if necessary
agent_auto () {
  local AGENT
  agent_running && return 0
  agent_env && return 0
  AGENT=$(agent_which) && agent_spawn $AGENT && return 0
  return 1
}
