#!/usr/bin/env sh

# Sleeps the computer
comp_sleep () {
  comp_lock || return 1
  sudo_wrap pm-suspend
}

# Powers down the computer
comp_off () {
  sudo_wrap poweroff
}

# Locks the screen
comp_lock () {
  run_quiet gnome-screensaver-command -l && return 0
  run_quiet xscreensaver-command -lock && return 0
  echo "Failed to lock the screen" >&2
  return 1
}
