#!/usr/bin/env sh
WM="$1"
[ "$WM" = "" ] || path_hasbin $WM && WM="xmonad"

if [ "$WM" = "awesome" ] || [ "$WM" = "Awesome" ]; then
  if [ -d ~/.config/wallpaper ]; then
	if [ "`ls ~/.config/wallpaper | wc -l`" -gt "1" ]; then
	  sleep 2
	  while true; do
		awsetbg -r ~/.config/wallpaper
		sleep 300
	  done &
	fi
  fi
  exec awesome
elif [ "$WM" = "xfce4" ]; then
  exec startxfce4
elif [ "$WM" = "xmonad" ] || [ "$WM" = "Xmonad" ]; then
  run_quiet hhp &
  exec xmonad
else
  exec $1
fi

# Determine which window manager is best suited
function graphical_bestwm {
  path_hasbin "xmonad" && { echo "xmonad"; return 0; }
  path_hasbin "awesome" && { echo "awesome"; return 0; }
  path_hasbin "startxfce4" && { echo "startxfce4"; return 0; }
  return 1
}

# Run the window manager with the best side apps
function graphical_runwm {
  # Run background applications
  run_quiet autocutsel -fork
  run_quiet pulseaudio --start
  run_quiet xscreensaver -no-splash &
  run_quiet VBoxClient-all
  run_quiet xcompmgr
  run_quiet setxkbmap -option ctrl:nocaps
  [ -f "$HOME/.xinitrc.start" ] && . "$HOME/.xinitrc.start"

  # Start the window manager
  exec $@

  # Kill the rest of the processes
  [ -f "$HOME/.xinitrc.end" ] && . "$HOME/.xinitrc.end"
  run_quiet pulseaudio --kill
}

# Automatically pick a window manager to run
function graphical_autorun {
  local WM
  if [ "$#" -ge "1" ]; then
    WM="$(echo "$1" | tr '[A-Z]' '[a-z]')"
    [ "$WM" = "awesomewm" ] && WM="awesome"
    [ "$WM" = "xfce4" ] && WM="startxfce4"
    path_hasbin "$WM" || WM=""
  fi
  [ -z "$WM" ] && WM="$(graphical_bestwm)"

  graphical_runwm $WM
}

# Automatically Configures the graphical interface
function graphical_auto {
  install -dv $HOME/.config
  rm -f $HOME/.{Xdefaults,gtkrc-2.0,config/{gtk-3.0,sakura}}
  config_ln xinitrc xsession xmonad config/{awesome,Terminal,wallpaper,uzbl}
  return 0
}
