#!/usr/bin/env sh

# Determine if this is a workstation
info_ws () {
  [ "$WS" -eq "0" ] && return 0
  [ "$(hostname -s | grep -e "\(wl\|wn\|wd\|dev\|fantom\)")" != "" ]
}

# Determine if the user is root
info_root () {
  [ "$(id -u)" -eq 0 ]
}
