#!/usr/bin/env sh

# Determine if this is a workstation
info_ws () {
  [ "$WS" = "0" ] && return 0
  hostname | grep -q "^\(prodigy\|legend\|fantom\|kennington\|exodus\)"
}

# Determine if the user is root
info_root () {
  [ "$(id -u)" -eq 0 ]
}
