#!/usr/bin/env sh

# Determine if this is a workstation
info_ws () {
  [ "$(hostname -s | grep -e "\(wl\|wn\|wd\|dev\|fantom\)")" != "" ]
}

# Determine if the user is root
info_root () {
  [ "$UID" -eq 0 ]
}
