#!/usr/bin/env sh

# Setup the colors for the shell
function shell_colors {
  # Colors for LS
  os_matches '\(Linux\|Cygwin\)' && eval "$(dircolors -b)" && alias ls='ls --color=auto'
  os_matches '\(FreeBSD\)' && export CLICOLOR=1 && export LSCOLORS="ExGxFxdxCxDhDxaBadaCeC"

  # 256 Colors in the Terminal
  if [ "$TERM" = "xterm" ] || [ "$TERM" = "rxvt-unicode-256color" ]; then
    export TERM="xterm-256color"
    unset COLORTERM
  fi
}

# Create the temporary directory for the shell
function shell_tmp {
  local TMP
  if TMP="$(dir_tmp)"; then
    export HISTFILE="$TMP/history_$(basename $SHELL)"
    export SAVEHIST="9999"
    echo "set viminfo+=n$TMP/viminfo" > $HOME/.vimrc.info
  else
    unset HISTFILE
    export SAVEHIST="0"
    echo "set viminfo=\"\"" > $HOME/.vimrc.info
  fi
}

# Initializes useful functions if the caller is a shell
function shell_init {
  shell_tmp
  shell_colors
  path_add "$HOME/.bin"
  path_add "$HOME/.cabal/bin"
  agent_auto

  alias gpa="git pull origin master; git submodule foreach --recursive \"(git checkout master; git pull origin master)&\""
  alias root="sudo_wrap su -"
  alias sprunge="curl -F 'sprunge=<-' http://sprunge.us" 
  alias t='laptop_bat; date'

  export EDITOR="vim"
  export PAGER="less"
  export BLOCKSIZE="K"
}

# Returns the name of the preferred shell
function shell_get_best {
  # ZSH preferred
  if which zsh >/dev/null 2>&1; then
    VER="$(zsh --version | awk '{print $2}')"
	VER="$(printf "4.3.9\n%s" "$VER" | sort -bt. -k1,1n -k2,2n -k3,3n -k4,4n -k5,5n | awk 'NR==1')"
	if [ "$VER" = "4.3.9" ]; then
      echo "zsh"
      return 0
    fi
  fi

  # Bash next
  if which bash >/dev/null 2>&1; then
    echo "bash"
    return 0
  fi

  # Fallback to SH
  echo "sh"
}

# Automatically executes the preferred shell
function shell_best {
  if [ "$(shell)" != "$(shell_get_best)" ]; then
    $(shell_get_best) $@
    exit $?
  fi
}

# Set the given shell as the default shell if not already set
function shell_default {
  [ "$#" -ne "1" ] && return 1
  chsh -s "$1" "$USER"
}

# Automatically configures the shell configuration files
function shell_auto {
  config_ln "bash_profile" "bashrc" "bash_logout" "zshrc" "zprofile" "zlogout"
  shell_default "$(shell_get_best)"
}
