#!/usr/bin/env zsh
OPENSSL=openssl

BINS="$(which -a openssl)"
VERS=""
for BIN in $BINS; do
	VERS="${VERS}$($BIN version | awk '{print $2}') $BIN\n"
done
VERS="${VERS}0.0.0a\n1.0.0e\n0.9.8x"
BEST="$(echo "$VERS" | sort -Vr | head -n 1)"
OPENSSL="$(echo "$BEST" | awk '{print $2}')"
echo "Using Openssl: $BEST"
