#!/usr/bin/env bash
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load the configuration options
. "$(readlink -f $(dirname $(readlink -f ~/.bashrc))/../)/lib/loader"
shell_best $@
shell_init
shell_theme
