#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Load the configuration options
. "$(readlink -f $(dirname $(readlink -f ~/.bashrc))/../)/lib/loader"
shell_best $@
shell_init
shell_theme

# Load the local config
[ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
