#!/bin/sh
SER="serial.txt"

if [[ ! -d "keys" ]]; then
	echo "You must run ./build-ca first"
	exit 1
fi
if [[ ! -f "$SER" ]]; then
	echo "Missing ${SER}, something might have gone wrong"
	exit 1
fi
if [[ "$#" != "2" || ("$1" != "gen" && "$1" != "csr")]]; then
	echo "Invalid Arguments: ./build-client gen|csr [filename]"
	exit 1
fi

PRE="keys/${2}"
CSR="${PRE}.csr"
KEY="${PRE}.key"
CRT="${PRE}.crt"

if [[ "$1" == "csr" && ! -f "$CSR" ]]; then
	echo "The certificate request [${CSR}] does not exist!"
	exit 1
fi

if [ "$1" == "gen" ]; then
	if [[ -f "$KEY" || -f "$CSR" || -f "$CRT" ]]; then
		read -p "${PRE} already exists, do you want to overwrite? [y|N] " ret
		if [[ "$ret" = "y" || "$ret" = "Y" ]]; then
			rm -f "$KEY"
			rm -f "$CSR"
			rm -f "$CRT"
		else
			echo "Will not continue generating ${PRE}"
			exit 1
		fi
	fi
	stty -echo
	read -p "Password: " pass
	echo ""
	read -p "Confirm: " pass2
	echo ""
	stty echo
	if [ "$pass" != "$pass2" ]; then
		echo "Passwords do not match"
		exit 1
	fi
	touch "$KEY"
	chmod 0600 "$KEY"
	if [ "$pass" = "" ]; then
		openssl genrsa -out "$KEY" 4096
		openssl req -new -config openssl.cnf -extensions v3_req -sha512 -key "$KEY" -out "$CSR"
		if [ "$?" != "0" ]; then
			echo "Certificate Request Generation Failed"
			exit 1
		fi
	else
		openssl genrsa -aes256 -passout "pass:${pass}" -out "$KEY" 4096
		openssl req -new -passin "pass:${pass}" -config openssl.cnf -extensions v3_req -sha512 -key "$KEY" -out "$CSR"
		if [ "$?" != "0" ]; then
			echo "Certificate Request Generation Failed"
			exit 1
		fi
	fi
fi
NUM=$(cat "$SER")

stty -echo
read -p "CA Password: " pass
echo ""
stty echo

openssl x509 -req -passin "pass:${pass}" -sha512 -extfile openssl.cnf -extensions usr_cert -set_serial "$NUM" -CA "keys/ca.crt" -CAkey "keys/ca.key" -in "$CSR" -out "$CRT"
if [ "$?" != "0" ]; then
	echo "Certificate Signing Failed"
	exit 1
fi
echo $(($NUM+1)) > "$SER"
