#!/bin/sh
if [ -d "keys" ]; then
	read -p "Key folder already exists, Delete and Continue? [y|N] " ret
	if [[ "$ret" = "y" || "$ret" = "Y" ]]; then
		rm -rf keys
	else
		echo "Will not continue generating ca"
		exit 1
	fi
fi
rm -rf serial.txt
stty -echo
read -p "Password: " pass
echo ""
read -p "Confirm: " pass2
echo ""
stty echo
if [ "$pass" != "$pass2" ]; then
	echo "Passwords do not match"
	exit 1
fi
if [ "$pass" = "" ]; then
	echo "You must provide a password for a CA"
	exit 1
fi
mkdir keys
touch keys/ca.key
chmod 0600 keys/ca.key
openssl genrsa -aes256 -passout "pass:${pass}" -out "keys/ca.key" 4096
openssl req -new -x509 -sha512 -passin "pass:${pass}" -config openssl.cnf -extensions v3_ca -key "keys/ca.key" -out "keys/ca.crt"
if [ "$?" != "0" ]; then
	echo "Failed to Create CA Certificate"
	exit 1
fi
echo "1" > serial.txt
