#!/usr/bin/env sh

# Retrieve the agent environment
function agent_file {
  echo "$(dir_tmp)/agent-environment"
}

# Print cmd if agent exists
function agent_cmd {
  [ "$#" -lt "1" ] && return 1
  path_hasbin $1 && echo $@
}

# Determine which agent to use
function agent_which {
  [ "$SSH_TTY" = "" ] && agent_cmd gpg-agent --daemon --enable-ssh-support && return 0
  agent_cmd ssh-agent && return 0
  echo "Failed to find an agent" >&2
  return 1
}

# Import already running agent data
function agent_tryenv {
  [ -S "$SSH_AUTH_SOCK" ] && return 0
  [ -f "$(agent_file)" ] && . "$(agent_file)"
  [ -S "$SSH_AUTH_SOCK" ] && return 0
  return 1
}

# Spawn agent if it doesn't exist
function agent_spawn {
  echo "Spawning $@"
  (eval "$@") | grep -v echo > "$(agent_file)"
  . "$(agent_file)"
  ssh-add
}

# Automatically determines which agent to use and starts it if necessary
function agent_auto {
  local AGENT
  agent_tryenv && return 0
  AGENT=$(agent_which) && agent_spawn $AGENT && return 0
  return 1
}
