#!/usr/bin/env sh

# Gets the latest version of the git config
function config_latest {
  echo ""
}

# Updates the configuration files and all of the submodules
function config_update {
  config_latest
  ssh_auto
}
