#!/usr/bin/env sh

# Run the command silently
function run_quiet {
  which $1 >/dev/null 2>&1 && $@ >/dev/null 2>&1
}

# Make sure the symbolic link points to the correct location $2 -> $1
function symlink {
  if [ "$(readlink -f "$2")" != "$1" ]; then
    rm -rf "$2"
    ln -s "$1" "$2" 2>/dev/null || return 1
  fi
}

# Get the path to the temporary directory
function dir_tmp {
  local DIRS;
  to_array DIRS "/dev/shm /run/shm /tmp /var/tmp"
  for I in $DIRS; do
	[ -w "$I" ] && (mount | grep '\(tmpfs\|ramfs\)' | grep $I >/dev/null) && DIR_TMP="$I/$USER" && break
  done
  [ "$DIR_TMP" = "" ] && (echo "Failed to find a temporary folder" >&2) && return 1
  [ ! -d "$DIR_TMP" ] && mkdir "$DIR_TMP" && chmod 0700 "$DIR_TMP"
  symlink "$DIR_TMP" "$HOME/.tmp"
  echo "$DIR_TMP"
}

# Tests to see if a binary exists in the path
function path_hasbin {
  [ "$#" -ne "1" ] && return 2
  [ "$(which $1 2>/dev/null | grep -v "not found")" != "" ]
}

# Add to the path if the DIR doesn't exist
function path_add {
  if [ "$(echo "$PATH" | grep "$1" 2>/dev/null)" = "" ]; then
    export PATH="${PATH}:$1"
  fi
}

# Wraps the command in sudo if sudo exists and runs it
function sudo_wrap {
  if path_hasbin sudo; then
    sudo $@
  else
    $@
  fi
}
