#!/usr/bin/env sh

# Gets the string representing the state of the battery
function laptop_bat {
  local B; local BAT_DIR
  BAT_DIR="/sys/class/power_supply/BAT*"
  B="$(cat $BAT_DIR/status 2>/dev/null)" || return 1
  ([[ "$B" == "Charging" ]] && echo "↑") || ([[ "$B" == "Discharging" ]] && echo "↓") || echo "⚡"
  echo "$(expr $(cat $BAT_DIR/charge_now) \* 100 / $(cat $BAT_DIR/charge_full))%"
}
