#!/usr/bin/env zsh
KEYDIR="keys"
SER="$KEYDIR/serial.txt"
source ./opts

if [ -d "$KEYDIR" ]; then
	echo -n "Key folder \"${KEYDIR}\" already exists, Delete and Continue? [y|N] "
	read ret
	if [[ "$ret" = "y" || "$ret" = "Y" ]]; then
		rm -rf "$KEYDIR"
	else
		echo "Will not continue generating ca"
		exit 1
	fi
fi
rm -f "$SER"
stty -echo
echo -n "Password: "
read pass
echo ""
echo -n "Confirm: "
read pass2
echo ""
stty echo
if [ "$pass" != "$pass2" ]; then
	echo "Passwords do not match"
	exit 1
fi
if [ "$pass" = "" ]; then
	echo "You must provide a password for a CA"
	exit 1
fi
mkdir "$KEYDIR"
touch "${KEYDIR}/ca.key"
chmod 0600 "${KEYDIR}/ca.key"
openssl genrsa -aes256 -passout "pass:${pass}" -out "${KEYDIR}/ca.key" 4096
openssl req -new -x509 -sha512 -passin "pass:${pass}" -config openssl.cnf -extensions v3_ca -key "${KEYDIR}/ca.key" -out "${KEYDIR}/ca.crt"
if [ "$?" != "0" ]; then
	echo "Failed to Create CA Certificate"
	exit 1
fi
echo "1" > "$SER"
