#!/usr/bin/env sh

test_os_issue_none () {
  return 1
}
test_register test_os_issue_none

test_os_issue_valid () {
  return 1
}
test_register test_os_issue_valid

test_os_matches () {
  return 1
}
test_register test_os_matches

test_os_nomatches () {
  return 1
}
test_register test_os_nomatches
