#
# ~/.bash_profile
#
#EMACS STUFF
WHO=`whoami`
RET=`pgrep -flu ${WHO} "emacs --daemon"`
EMACS=`which emacs`
if [[ "0" -eq "$?" && "${RET}" = "" ]]; then
	RET=`${EMACS} --help | grep daemon`
	if [ "${RET}" != "" ]; then
		emacs --daemon > /dev/null 2>&1
	fi
fi

#OTHER STUFF
[[ -f ~/.bashrc ]] && . ~/.bashrc
