#!/usr/bin/env sh

# Try to locate the base git directory for the given file
function dir_conf_try {
  cd "$(dirname "$(readlink -f "$1")")" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null && return 0
  return 1
}

# Determines the top level configuration directory
function dir_conf {
  dir_conf_try "$1" && return 0
  dir_conf_try "~/.zshrc" && return 0
  dir_conf_try "~/.bashrc" && return 0
  echo "Failed to find the configuration directory" >&2
  return 1
}

# Creates an array from the name of the variable and values
function to_array {
  ([ "$#" -lt "1" ] || [ "$#" -gt "2" ]) && return 1

  # Read in the array data
  local DATA
  if [ "$#" -eq "1" ]; then
    DATA="$(cat -)"
  else
    DATA="$2"
  fi

  # Convert the data into an array
  if [ "$(ps hp $$ | awk '{print $5}')" = "zsh" ]; then
    eval "$1=($DATA)"
  else
    eval "$1=\"$DATA\""
  fi
}

# Source Modules
to_array MODS "$(find $(dir_conf $0)/base/mod -type f)"
for M in $MODS; do
  [ "$(echo "$M" | grep '\(~$\|^#\)')" != "" ] && continue
  . "$M"
done
