#!/usr/bin/env sh

# Creates an array from the name of the variable and values
function to_array {
  ([ "$#" -lt "1" ] || [ "$#" -gt "2" ]) && return 1

  # Read in the array data
  local DATA
  if [ "$#" -eq "1" ]; then
    DATA="$(cat -)"
  else
    DATA="$2"
  fi

  # Convert the data into an array
  if [ "$(ps hp $$ | awk '{print $5}')" = "zsh" ]; then
    eval "$1=($DATA)"
  else
    eval "$1=\"$DATA\""
  fi
}

# Source Modules
to_array MODS "$(find $CONF/base/mod -type f)"
for M in $MODS; do
  [ "$(echo "$M" | grep '\(~$\|^#\)')" != "" ] && continue
  . "$M"
done
