#!/bin/sh
#XTERM
if [ "${TERM}" = "xterm" ]; then
	export TERM=xterm-256color
elif [ "${TERM}" = "rxvt-unicode-256color" ]; then
	export TERM=xterm-256color
	unset COLORTERM
fi

#UPDATE CMD
UN="$(uname)"
if [ "$UN" = "Linux" ]; then
	ISSUE=$(cat /etc/issue)
	if [ "$(echo "$ISSUE" | grep "Arch Linux")" != "" ]; then
		if [ "$(which packer 2>/dev/null | grep "not found")" = "" ]; then
			alias update='packer -Syu'
			alias inst='packer -S'
		else
			alias update='sudo pacman -Syu'
			alias inst='sudo pacman -S'
		fi
		alias clean='if [ "$(pacman -Qqdt)" != "" ]; then; sudo pacman -Rns $(pacman -Qqdt); fi'
	elif [ "$(echo "$ISSUE" | grep "Debian")" = "" ]; then
		alias update='apt-get update; apt-get upgrade-dist'
		alias inst='apt-get install'
	fi
elif [ "$UN" = "FreeBSD" ]; then
	if [ "$(which portmaster 2>/dev/null | grep "not found")" = ""]; then
		alias inst='sudo portmaster -y'
		alias update='sudo portsnap fetch; sudo portsnap update; sudo portmaster -ay'
	else
		alias update='sudo portsnap fetch; sudo portsnap update'
	fi
fi

#ROOT
alias root="sudo su -"

#SSH AUTH INIT
SOCKFILE=$HOME/.ssh/environment-$HOST
if [ "${SSH_AUTH_SOCK}" = "" ]; then
	if [ -f $SOCKFILE ]; then
		source "$SOCKFILE"
		kill -0 "$SSH_AGENT_PID" >/dev/null 2>&1
		if [ "$?" != "0" ]; then
			rm "$SOCKFILE"
		fi
	fi
	if [ ! -f $SOCKFILE ]; then
		echo "$(ssh-agent | grep -v "echo")" > "$SOCKFILE"
		source "$SOCKFILE"
		ssh-add
	fi
fi

#EMACS STUFF
EMACS=`which emacs 2> /dev/null`
RET=`${EMACS} --help 2> /dev/null | grep daemon`
if [ "${RET}" != "" ]; then
	alias emacs="$(which emacsclient) -t"
	kill -0 $(cat ~/.emacs.pid 2>/dev/null) 2>/dev/null
	if [ "$?" != "0" ]; then
		echo "Starting the Emacs Daemon"
		$EMACS --daemon >/dev/null 2>&1
	fi
fi
